Fixing workflow for testing as a github action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -87,7 +87,8 @@ runs:
         --detach
         --rm
         --name teamengine
-        --network host
+        --add-host=host.docker.internal:host-gateway
+        --publish 9080:8080
         ogccite/teamengine-production:1.0-SNAPSHOT
     - name: "Run cite-runner"
       id: "run_cite_runner"
@@ -98,12 +99,16 @@ runs:
         uv run cite-runner \
             --network-timeout=${{ inputs.network_timeout_seconds }} \
             execute-test-suite-from-github-actions \
-            ${{ inputs.teamengine_url || 'http://localhost:8080/teamengine' }} \
+            ${{ inputs.teamengine_url || 'http://localhost:9080/teamengine' }} \
             ${{ inputs.test_suite_identifier }} \
             --output-format=raw \
             --teamengine-username=${{ inputs.teamengine_username }} \
             --teamengine-password=${{ inputs.teamengine_password }} \
             $(echo -e ${{ inputs.test_session_arguments }}) 1> ${RAW_PATH}
+        if [ $? -ne 0 ]; then
+            echo "Unable to use TeamEngine to execute test suite ${{ inputs.test_suite_identifier }} with arguments ${{ inputs.test_session_arguments }}"
+            exit 1
+        fi
         echo "RAW_RESULT_OUTPUT_PATH=${{ github.action_path }}/${RAW_PATH}" >> "${GITHUB_OUTPUT}"
         echo "::group::cite-runner suite execution results"
         uv run cite-runner parse-result \
@@ -127,15 +132,14 @@ runs:
         cat ${MARKDOWN_PATH} >> ${GITHUB_STEP_SUMMARY}
         echo "MARKDOWN_RESULT_OUTPUT_PATH=${{ github.action_path }}/${MARKDOWN_PATH}" >> "${GITHUB_OUTPUT}"
     - name: "Store execution results as artifacts"
-      if: ${{ !cancelled() }}
       uses: actions/upload-artifact@v4
       with:
         name: 'execution-results-${{ inputs.test_suite_identifier }}'
         path: |
           ${{ steps.run_cite_runner.outputs.RAW_RESULT_OUTPUT_PATH }}
           ${{ steps.run_cite_runner.outputs.MARKDOWN_RESULT_OUTPUT_PATH }}
-    - name: "Stop TEAM engine container"
-      if: ${{ !cancelled() && !inputs.teamengine_url }}
+    - name: "Stop teamengine container"
+      if: ${{ always() && !inputs.teamengine_url }}
       shell: "bash"
       run: docker stop teamengine
     - name: "Set action exit code"
