Fixing workflow for testing as a github action

diff --git a/.github/workflows/test-action.yaml b/.github/workflows/test-action.yaml
--- a/.github/workflows/test-action.yaml
+++ b/.github/workflows/test-action.yaml
@@ -1,10 +1,50 @@
-name: Continuous Integration
+name: Test cite-runner as a GitHub action
+
+on:
+  # will run both when pushing a branch and when pushing a tag
+  push:
+
+  pull_request:
+
+  # will run when called from another workflow
+  workflow_call:
 
 env:
   COLUMNS: 120
 
 jobs:
-  run_ci:
+  test_cite_runner_github_action:
     runs-on: ubuntu-24.04
+    env:
+      SIMPLESERVER_PORT: 8000
     steps:
-      - name: "launch test server"
+      - name: "Grab code"
+        uses: actions/checkout@v4.2.2
+      - name: "Set up Python"
+        uses: actions/setup-python@v5
+        with:
+          python-version-file: "pyproject.toml"
+      - name: "Launch simple test server"
+        run: |
+          python tests/simpleserver.py --bind-port ${{ env.SIMPLESERVER_PORT }} > /dev/null &
+          echo $! > simpleserver.pid
+          sleep 3
+          if ps --pid $(cat simpleserver.pid) > /dev/null; then
+              echo "simpleserver is up and running with PID $(cat simpleserver.pid)"
+          else
+              echo "simpleserver failed to start"
+              exit 1
+          fi
+      - name: "Test cite-runner GitHub action"
+        uses: ./
+        with:
+          test_suite_identifier: ogcapi-features-1.0
+          test_session_arguments: iut=http://localhost:${{ env.SIMPLESERVER_PORT }}
+      - name: "Shut down simple test server"
+        if: always()
+        run: |
+          if [ -f server.pid ]; then
+              echo "Shutting down simpleserver with PID $(cat simpleserver.pid)..."
+              kill $(cat simpleserver.pid) || true
+              rm simpleserver.pid
+          fi
